---
title: "HDT4_RML"
author: "Alejandro Alvarez, Jorge De Leon, Roberto Castillo"
date: '2022-03-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE,warning=FALSE}
library("tidyverse")
library("dplyr")
library("ggplot2")
library("httr")
library("readr")
library(rpart)
library(caret)
library(randomForest)
library(tree)
library(rpart.plot)
library(car)
library(cluster) #Para calcular la silueta
library(e1071)#para cmeans
library(mclust) #mixtures of gaussians
library(fpc) #para hacer el plotcluster
library(NbClust) #Para determinar el número de clusters óptimo
library(factoextra) #Para hacer gráficos bonitos de clustering
library(hopkins) #Para revisar si vale la pena hacer agrupamiento
library(GGally) #Para hacer el conjunto de graficos
library(FeatureImpCluster) #Para revisar la importancia de las variables en los grupos.
library(pheatmap) #Para hacer mapa de calor
```

```{r}


house <- read.csv("./train.csv", stringsAsFactors = F)
quant <- quantile(house$SalePric)
```


```{r}
set.seed(123)
#se toman las variables que se cree predicen propiamente el precio de la casa y el precio real de la casa.
#luego se reemplaza la columna del precio de la casa por una que lo clasifica como economica, intermedio o cara dependiendo de los percentiles.
data <- fread("./train.csv", select = c("OverallQual","OverallCond" ,"GrLivArea", "BedroomAbvGr", "TotRmsAbvGrd", "GarageCars", "SalePrice", "YearBuilt", "LotArea", "LotFrontage"))
data <- data %>% mutate(Economica = if_else(quant["0%"] <= SalePrice & SalePrice < quant["25%"], 1,0))
data <- data %>% mutate(Intermedia = if_else(quant["25%"] <= SalePrice & SalePrice < quant["50%"], 1,0))
data <- data %>% mutate(Cara = if_else(quant["50%"] <= SalePrice, 1,0))

data$OverallQual[data$OverallQual == 'NAN'] <- 0



data
```
```{r}


#-----CORRELACIONES------#
# Correlación de 80.98%
cor(data$OverallQual,data$Cara, method = "spearman")
# Correlación de 69.07%
cor(data$GarageCars,data$Cara, method = "spearman")
# Correlación de 73.13%
cor(data$GrLivArea,data$Cara, method = "spearman")
# Correlación de 65.26%
cor(data$YearBuilt,data$Cara, method = "spearman")
```

```{r}

corte <- sample(nrow(data),nrow(data)*0.7)
train<-data[corte,]
test<-data[-corte,]


```

```{r}
modelo<-glm(train$Cara~., data = train[,c(1,3,6,8)], family = binomial(), maxit=100)
```
```{r}
pred<-predict(modelo,newdata = test[,c(1,3,6,8)], type = "response")
prediccion<-ifelse(pred>=0.5,1,0)
confusionMatrix(as.factor(test$Cara),as.factor(prediccion))
```


```{r}
pred<-predict(modelo,newdata = train[,c(1,3,6,8)], type = "response")
prediccion<-ifelse(pred>=0.5,1,0)
confusionMatrix(as.factor(train$Cara),as.factor(prediccion))
```
```{r}
#se concluye que no hay overfitting dado que no existe una discrepancia significativa entre la precisión del modelo con el set de test y el de train
```

```{r}
modelo2<-glm(train$Intermedia~., data = train[,c(1,3,6,8)], family = binomial(), maxit=100)
```
```{r}
pred<-predict(modelo2,newdata = test[,c(1,3,6,8)], type = "response")
prediccion<-ifelse(pred>=0.5,1,0)
confusionMatrix(as.factor(test$Intermedia),as.factor(prediccion))
```

```{r}
pred<-predict(modelo2,newdata = train[,c(1,3,6,8)], type = "response")
prediccion<-ifelse(pred>=0.5,1,0)
confusionMatrix(as.factor(train$Intermedia),as.factor(prediccion))
```
```{r}
modelo3<-glm(train$Economica~., data = train[,c(1,3,6,8)], family = binomial(), maxit=100)
```
```{r}
pred<-predict(modelo3,newdata = test[,c(1,3,6,8)], type = "response")
prediccion<-ifelse(pred>=0.5,1,0)
confusionMatrix(as.factor(test$Economica),as.factor(prediccion))
```

```{r}
pred<-predict(modelo3,newdata = train[,c(1,3,6,8)], type = "response")
prediccion<-ifelse(pred>=0.5,1,0)
confusionMatrix(as.factor(train$Economica),as.factor(prediccion))
```
